/**
 * Cross-channel loop guard.
 *
 * Outbound channel messages are tagged with an invisible sentinel so another
 * Sandra-managed account can recognise the message as agent-originated and
 * refuse to auto-reply. This prevents bot-to-bot ping-pong loops across
 * channels like email, WhatsApp, and Instagram.
 */

/** Invisible separator pair. Extremely unlikely to appear in human input. */
export const AGENT_LOOP_SENTINEL = '\u2063\u2064';

/** Email-only explicit header for transports that preserve RFC822 headers. */
export const AGENT_LOOP_HEADER = 'X-Sandra-Agent';

/**
 * Fallback signature detector for email transports that strip custom headers
 * and invisible sentinels. Matches the canonical footer generated by
 * buildEmailBody():
 *
 * --
 * <App Name>
 * AI Assistant
 */
const AGENT_SIGNATURE_PATTERN = /(?:^|\n)--\s*\n[^\n]{1,120}\nAI Assistant(?:\s|$)/i;

export function hasAgentLoopSentinel(content: string | null | undefined): boolean {
  return Boolean(content?.includes(AGENT_LOOP_SENTINEL));
}

export function tagAgentLoopSentinel(content: string): string {
  if (hasAgentLoopSentinel(content)) return content;
  return `${content}${AGENT_LOOP_SENTINEL}`;
}

export function stripAgentLoopSentinel(content: string): string {
  return content.replaceAll(AGENT_LOOP_SENTINEL, '').trimEnd();
}

export function hasAgentSignature(content: string | null | undefined): boolean {
  if (!content) return false;
  const normalized = content.replace(/\r\n/g, '\n');
  return AGENT_SIGNATURE_PATTERN.test(normalized);
}

export function hasAgentLoopHeader(
  headers: Record<string, string> | null | undefined,
): boolean {
  if (!headers) return false;

  const value = headers[AGENT_LOOP_HEADER]
    ?? headers[AGENT_LOOP_HEADER.toLowerCase()]
    ?? headers[AGENT_LOOP_HEADER.toUpperCase()];

  return value === '1' || value?.toLowerCase() === 'true';
}